/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "test_sine.h"
#include "fp_trig.h"
#include "init.h"

int main(void)
{
    DAC_Init();
    DMA_Init(dma_buffer, BUFFER_SIZE);
    Timer6_Init();
    Timer7_Init();

    // Start with the first frequency
    generate_and_fill_dma_buffer(frequencies[current_freq_index]);

    // Enable DMA for continuous output
    DAC->CR |= DAC_CR_DMAEN1;
    while(1)
    {
    }

	return 0;
}
