/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "test_sine.h"
#include "fp_trig.h"
#include "init.h"

int main(void)
{
	Generate_SineWave_440(SINE_TABLE_SIZE_440Hz);
	Generate_SineWave_587(SINE_TABLE_SIZE_587Hz);
	Generate_SineWave_659(SINE_TABLE_SIZE_659Hz);
	Generate_SineWave_880(SINE_TABLE_SIZE_880Hz);
	DMA_Init();
	Timer6_Init();
	Timer1_Init();
	ADC_INIT();
	DAC_Init();
	Systick_Init();


while(1){
    }

	return 0;
}
