/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "test_sine.h"
#include "fp_trig.h"
#include "init.h"

int main(void)
{
	SystemInit();

    DAC_Init();
    Timer6_Init();
    Timer7_Init();

    generate_sine_table(frequencies[0]);
    fill_dma_buffer();

    DMA_Init(dma_buffer, BUFFER_SIZE);
    while(1)
    {
    }

	return 0;
}
